# 1:- Chi_Square_test

Categorical Data: The data must be in categorical form, meaning it is divided into distinct categories.
These categories can be nominal (e.g., gender, color, type) or ordinal (e.g., rankings, scales).

Count Data: The test is applied to frequency counts of occurrences within the categories.
For instance, how many times different categories appear in a dataset.

### import librares

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
from scipy import stats

### load the data

In [2]:
df=sns.load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## Null Hypothesis (H0): There is no difference in the survival rates between male and female passengers on the Titanic.

## Alternative Hypothesis (H1): There is a difference in the survival rates between male and female passengers on the Titanic.

In [6]:
# Create a contingency Table
contingency_table=pd.crosstab(df['sepal_width']'sepal_length'], df['species'])
contingency_table

KeyError: ('sepal_width', 'sepal_length')

In [5]:
# preform chi_square test
chi2, p, dof, expected= stats.chi2_contingency(contingency_table)

print('chi_square: ', chi2)
print('P_value: ', p)
print('degree of freedom: ', dof)
print(f'Expected:\n {expected}')

chi_square:  89.54628704628703
P_value:  6.016031482207116e-05
degree of freedom:  44
Expected:
 [[0.33333333 0.33333333 0.33333333]
 [1.         1.         1.        ]
 [1.33333333 1.33333333 1.33333333]
 [1.         1.         1.        ]
 [2.66666667 2.66666667 2.66666667]
 [1.66666667 1.66666667 1.66666667]
 [3.         3.         3.        ]
 [4.66666667 4.66666667 4.66666667]
 [3.33333333 3.33333333 3.33333333]
 [8.66666667 8.66666667 8.66666667]
 [3.66666667 3.66666667 3.66666667]
 [4.33333333 4.33333333 4.33333333]
 [2.         2.         2.        ]
 [4.         4.         4.        ]
 [2.         2.         2.        ]
 [1.33333333 1.33333333 1.33333333]
 [1.         1.         1.        ]
 [2.         2.         2.        ]
 [0.66666667 0.66666667 0.66666667]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


Rejecting the null hypothesis at the 0.05 significance level means that
we have very strong evidence to suggest that survival rates were indeed
different between male and female passengers on the Titanic.
This supports the alternative hypothesis that female passengers had a higher likelihood of survival compared to male passengers.